name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main  # Main branch pe push hote hi deploy hoga

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            if [ -d "next-cicd/.git" ]; then
              cd next-cicd && git pull origin main
            else
              rm -rf next-cicd
              git clone https://github.com/sushilkumar666/next-cicd.git
              cd next-cicd
            fi
            npm install
            npm run build
            pm2 describe next-cicd > /dev/null 2>&1 && pm2 restart next-cicd || pm2 start "npm start" --name "next-cicd"


